apiVersion: v1
kind: ReplicationController
metadata:
  name: __NAME__-__VERSION__
spec:
  replicas: 1
  template:
    metadata:
      labels:
        version: "__VERSION__"
        site: __NAME__
    spec:
      containers:
      - name: silverstripe
        image: __REPO__:__VERSION__
        ports:
        - containerPort: 80
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
---
apiVersion: v1
kind: Service
metadata:
  name: __NAME__
  labels:
    version: "__VERSION__"
    site: __NAME__
spec:
  ports:
  - port: 80
  selector:
    version: "__VERSION__"
    site: __NAME__
